source 'https://github.com/CocoaPods/Specs.git'

target 'WCCheckbox_Example', :exclusive => true do
  pod 'WCCheckbox', :path => '../'
end

target 'WCCheckbox_Tests', :exclusive => true do
  pod 'WCCheckbox', :path => '../'

  
end
